framework:
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            product.cache:
                adapter: cache.adapter.redis
                public: true
                default_lifetime: 3600