when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/dev.log"
                level: debug
                channels: ["!event"]
                max_files: 10

when@test:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/test.log"
                level: debug
                channels: ["!event"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/prod.log"
                level: debug
                max_files: 10
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: "%kernel.logs_dir%/deprecation.log"