# config/services.yaml
parameters:
    app.pagination.limit: '%env(int:API_PAGINATION_LIMIT)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    App\Domain\Service\DiscountCalculator:
        autowire: true

    App\Domain\Service\DiscountStrategy\CategoryDiscountStrategy:
        autowire: true

    App\Domain\Service\DiscountStrategy\SkuDiscountStrategy:
        autowire: true

    App\Domain\Service\DiscountService:
        arguments:
            $strategies:
                - '@App\Domain\Service\DiscountStrategy\CategoryDiscountStrategy'
                - '@App\Domain\Service\DiscountStrategy\SkuDiscountStrategy'